hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("~/.config/waybar/launch.sh")
    hl.exec_cmd("swaync")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("sleep 1 && ~/.config/hypr/scripts/wallcycle.sh")
end)
